#!/usr/bin/env bash
# Displays "To infinity and beyond indefinitely"
# In between each iteration of the loop, add a sleep 2
while :
do
	echo "To infinity and beyond"
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done

