#!/usr/bin/env bash
# Displays the
# The content of the current directory
# In list format
# Where only the part of the name after the first dash is displayed
LIST="$(ls)"
for l in $LIST;
do
	echo "$l" | cut -d '-' -f 2
done
